In [1]:
import numpy as np
#create a 1d array
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [2]:
#acessing  an element from an array

arr1[2]


3

In [3]:
#change an element 
arr1[2]=5

In [4]:
arr1

array([1, 2, 5])

In [5]:
#create a 2d array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
#check the shape of array
print("The shape is 2 rows and 3 columns",arr2.shape)

The shape is 2 rows and 3 columns (2, 3)


In [7]:
#acessing the elements from the array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [8]:
# array of type string

arr3 = np.array(['India','china','usa','mexico'])
print(arr3)

['India' 'china' 'usa' 'mexico']


In [9]:
arr3[1]

'china'

In [10]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
arr=np.linspace(0,20,2)
print(arr)

[ 0. 20.]


In [12]:
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [13]:
arr = np.random.rand(10)
print(arr)
arr = np.random.rand(3,4)
print(arr)


[0.44242725 0.93114224 0.51032398 0.20957824 0.70350708 0.90589276
 0.61733926 0.18043593 0.22768083 0.99553231]
[[0.06245354 0.28417932 0.19109153 0.63707821]
 [0.83660377 0.66117999 0.22149402 0.18580868]
 [0.36654456 0.64737322 0.70079869 0.36218105]]


In [14]:
# array of constant values in a given shape

print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [15]:
#create an array by a repetition
#repeat each element of an array by a specified number of times

arr= [0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [16]:
arr= [0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [17]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
arr = np.random.rand(5,5)
print(arr)

[[0.11015432 0.08044598 0.31430968 0.11835313 0.90990866]
 [0.20430105 0.043307   0.52265423 0.13480663 0.0799356 ]
 [0.46632998 0.94396283 0.27330202 0.29697435 0.01850678]
 [0.86700828 0.81820994 0.09487309 0.94333383 0.68596676]
 [0.77521211 0.17841627 0.59564258 0.9461342  0.56966364]]


In [21]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
#sum along the column

print(np.sum(arr,axis=0))

[2.42300574 2.06434202 1.80078161 2.43960214 2.26398145]


In [23]:
#sum along the row

print(np.sum(arr,axis=0))

[2.42300574 2.06434202 1.80078161 2.43960214 2.26398145]


In [24]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.4396685180632295
0.31430968437131934
0.3309135870751901
0.10950380211096941


In [25]:
#sort an array
arr=np.random.rand(5,5)
print(arr)

[[0.26193199 0.89595918 0.4111388  0.30071062 0.46678095]
 [0.54356282 0.26328204 0.75168834 0.10233977 0.72115107]
 [0.01993091 0.70094388 0.7570547  0.98396245 0.83894589]
 [0.01407101 0.42405131 0.52280782 0.60650983 0.80146247]
 [0.95641999 0.92185406 0.05426353 0.72463936 0.02285753]]


In [26]:
#sorting along the row


print(np.sort(arr,axis=1))

[[0.26193199 0.30071062 0.4111388  0.46678095 0.89595918]
 [0.10233977 0.26328204 0.54356282 0.72115107 0.75168834]
 [0.01993091 0.70094388 0.7570547  0.83894589 0.98396245]
 [0.01407101 0.42405131 0.52280782 0.60650983 0.80146247]
 [0.02285753 0.05426353 0.72463936 0.92185406 0.95641999]]


In [27]:
#append elements to an array
arr = np.array([4,5,6,7])

In [28]:
arr1 = np.append(arr,8)
arr1


array([4, 5, 6, 7, 8])

In [29]:
arr2 = np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [30]:
#delete multiple elements
arr2 = np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [31]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])

In [32]:
cat = np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [33]:
cat = np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
